name: UPS Tracker

on:
  schedule:
    - cron: "*/60 * * * *"   # every 10 minutes
  workflow_dispatch:          # allow manual run

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests twilio

      - name: Run UPS tracker
        env:
          UPS_CLIENT_ID: ${{ secrets.UPS_CLIENT_ID }}
          UPS_CLIENT_SECRET: ${{ secrets.UPS_CLIENT_SECRET }}
          UPS_TRACKINGS: ${{ secrets.UPS_TRACKINGS }}
          UPS_NICKNAMES: ${{ secrets.UPS_NICKNAMES }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_PHONE: ${{ secrets.TWILIO_PHONE }}
          MY_PHONE: ${{ secrets.MY_PHONE }}
        run: python main.py
